title: Julia Persson | HealthTech Innovator | AI-Augmented Venture Designer
email: julia@happylongevity.life
description: >- 
  Digital Transformation Leader and HealthTech Innovator dedicated to democratising 
  health optimisation through AI and data-driven solutions. Founder of HappyLongevity.
baseurl: "https://www.happylongevity.life/blog" # the subpath of your site, e.g. /blog
url: "https://JuliaHappyLongevity.github.io" # the base hostname & protocol

# Build settings
theme: modern-resume-theme

# Social links
github_username: JuliaHappyLongevity
linkedin_username: julia-persson-digital-transformation

# About Section
about_title: About Me
about_profile_image: images/JP_founder.jpeg
about_content: | 
  Dedicated to democratising health optimisation, I focus on transforming complex health data into clear, actionable
  insights through AI technology and scientific frameworks.

  Drawing on decades of experience in digital transformation and strategic business execution, combined with an
  extensive personal health optimisation journey, I work to empower everyone to understand their health patterns and
  take early action.

  Through HappyLongevity, AI-Powered Longevity Navigation Platform, we will deliver AI-enabled, data-driven insights and practical solutions that make preventive
  health optimisation accessible and understandable for all - because staying healthy shouldn't require a medical degree.

# Additional settings
darkmode: false
sass:
  sass_dir: _sass
  style: compressed

# Content settings
header_title: Julia Persson
header_subtitle: Digital Transformation Leader | HealthTech Innovator | AI-Augmented Venture Designer