# Site
repository: JuliaHappyLongevity/JuliaHappyLongevity.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Julia Persson
title: AI & Data Science Leader | HealthTech Innovator | Longevity Platform Founder
email: julia@happylongevity.life
description: >- 
  Building an AI-powered health optimization platform seeking exceptional data scientists and ML engineers.
  We're leveraging advanced analytics, deep learning, and predictive modeling to transform biomarker data
  into personalized health insights and actionable recommendations. Join our mission to democratize
  longevity science through innovative data approaches.
website: https://juliahappylongevity.github.io
baseurl: ""
url: "https://juliahappylongevity.github.io"

# Build settings
remote_theme: sproogen/modern-resume-theme

# Social links
github_username: JuliaHappyLongevity
linkedin_username: julia-persson-digital-transformation

# Phone info
phone: "+45 5030 3255 | +46 79 078 4001 (WhatsApp)"

# Content sections
content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: HappyLongevity.Life
        sub_title: Founder
        caption: July 2024 - Present
        link: https://happylongevity.life
        description: |
          Building a data-driven health optimization platform, integrating biomarkers, wearables, and AI. Developing scientific validation frameworks, focusing on longevity and preventive healthcare.
          
          - Implementing AI-driven health analysis and personalized recommendations
          - Creating data integration frameworks for biomarkers and wearable devices
          - Developing digital marketing, SEO strategy, and online community
          - Building scientific validation protocols with multi-LLM architecture
          
      - layout: right
        title: Accenture
        sub_title: Managing Director, Nordic Cloud Financial Services and Health & Public Sector Lead
        caption: Sep 2021 - March 2025
        link: https://www.accenture.com
        description: |
          Led regulated industries portfolio (Financial Services, Public Sector & Healthcare) managing cloud adoption, digital transformation and large-scale migrations.
          
          - Aligned technology strategies with compliance requirements
          - Managed global engagements across financial services, healthcare, and public sector
          - Implemented data-driven decision frameworks for enterprise clients
          
      - layout: right
        title: Amazon Web Services (AWS)
        sub_title: Financial Services Lead
        caption: Feb 2019 - Aug 2021
        link: https://aws.amazon.com
        description: |
          Achieved exponential growth in Nordic FS through data-driven strategy and cloud adoption.
          
          - Led major cloud transformation projects for banks, insurers, and pension providers
          - Implemented enterprise-scale data and analytics solutions
          - Developed scalable architectures for regulated industries
          - Created strategic technology roadmaps for digital transformation
          
      - layout: right
        title: Swedbank
        sub_title: Head of Cash Management, Large Corporates & Institutions
        caption: Apr 2013 - Jan 2019
        link: https://www.swedbank.com
        description: |
          Delivered revenue growth, increasing client engagement through digital innovation.
          
          - Led business transformation programs
          - Aligned financial services with digital technology
          - Implemented data-driven client solutions
          - Optimized operational efficiency through technology
          
      - layout: right
        title: A.P. Moller-Maersk
        sub_title: Deputy Head of Corporate Treasury
        caption: Jan 2007 - Mar 2013
        link: https://www.maersk.com
        description: |
          Managed global banking operations across 120+ countries, optimizing cash management.
          
          - Improved liquidity visibility to 87%
          - Reduced idle cash below 10% during the financial crisis
          - Implemented global treasury systems
          - Standardized financial processes across regions
          
  - title: Projects
    layout: list
    content:
      - layout: left
        title: HappyLongevity Platform
        link: https://happylongevity.life
        link_text: HappyLongevity.life
        additional_links:
          - title: JuliaHappyLongevity/JuliaHappyLongevity.github.io
            icon: fab fa-github
            url: https://github.com/JuliaHappyLongevity/JuliaHappyLongevity.github.io
        quote: >
          AI-Powered Longevity Navigation Platform - Seeking Data Science Talent
        description: |
          An AI-powered Longevity Navigation platform integrating biomarkers, genetic data, wearables, and lifestyle factors to provide early health risk detection and personalized recommendations.
          
          - Multi-LLM architecture for scientifically validated health analysis
          - Integration with wearables and lab testing services
          - Personalized health dashboards and intervention plans
          - Early risk detection and prevention-focused recommendations
      
      - layout: left
        title: Nordic Women's Health Hub
        quote: >
          Volunteer Initiative
        description: |
          Co-leading Nordic Women's Health Vision 2040, a volunteer initiative to improve women's health outcomes through technology, education, and policy.
      
      - layout: left
        title: ReDI School of Digital Integration
        quote: >
          Volunteer Initiative
        description: |
          Teaching technology fundamentals to women from foreign backgrounds, empowering them with digital skills for career advancement.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Lund University
        sub_title: MSc in Business & Economics
        caption: Sweden
      
      - layout: top-right
        title: Kyiv National Economic University
        sub_title: MSc in Business Administration
        caption: Ukraine
          
  - title: Skills
    layout: text
    content: |
      <h4>HealthTech & Digital Innovation</h4>
      <ul class="skill-list">
        <li>AI-powered, data-driven health solutions</li>
        <li>Preventive healthcare platforms</li>
        <li>Health data analytics and integration</li>
        <li>Personalized health recommendations</li>
      </ul>
      
      <h4>Cloud & AI Strategy</h4>
      <ul class="skill-list">
        <li>Cloud infrastructure and architecture</li>
        <li>AI implementation and automation</li>
        <li>Data-driven decision frameworks</li>
        <li>Enterprise digital transformation</li>
      </ul>
      
      <h4>Business & Leadership</h4>
      <ul class="skill-list">
        <li>Global transformation initiatives</li>
        <li>Strategic business execution</li>
        <li>Cross-functional team leadership</li>
        <li>Change management and implementation</li>
      </ul>
      
  - title: Certifications & Languages
    layout: text
    content: |
      <h4>Certifications</h4>
      <ul class="certification-list">
        <li>MIT Sloan – Green Cloud & Business Transformation</li>
        <li>Harvard Business School – Disruptive Strategy & Leadership in Change</li>
        <li>AWS Cloud Practitioner</li>
        <li>IMD – Financial Leadership Program</li>
      </ul>
      
      <h4>Languages</h4>
      <ul class="language-list">
        <li><strong>English:</strong> Fluent</li>
        <li><strong>Swedish:</strong> Fluent</li>
        <li><strong>Ukrainian:</strong> Fluent</li>
        <li><strong>Russian:</strong> Fluent</li>
        <li><strong>Danish:</strong> Conversational</li>
      </ul>

# About Section
about_title: About Me
about_profile_image: /images/JP_founder.jpeg
about_content: | 
  ## HappyLongevity Mission

  **Democratizing health optimization through AI and data-driven insights**

  At HappyLongevity, we're building an AI-powered Longevity Navigation platform that makes preventive health accessible to everyone. By transforming complex health data into clear, actionable insights, we empower individuals to understand their health patterns and take early action - because staying healthy shouldn't require a medical degree.

  ## Our Approach

  - **Scientific Validation** - Rigorous frameworks based on medical research
  - **AI-Powered Analysis** - Multi-LLM architecture for reliable health insights
  - **Data Integration** - Biomarkers, genetics, wearables, body composition scans, family medical history and lifestyle
  - **Personalized Recommendations** - Tailored health optimization strategies
  - **Early Risk Detection** - Identifying patterns before they become problems

  ## Technology Focus

  - **Data Integration Frameworks** - Connecting diverse health data sources
  - **AI Model Validation** - Ensuring scientific accuracy in health analysis
  - **Cloud-Based Architecture** - Scalable, secure healthcare solutions
  - **User Experience Design** - Making complex health data understandable

# Dark Mode (true/false/never)
darkmode: false

# Google Analytics
google_analytics: G-EMBYLELM4B  # Replace with your actual Google Analytics ID

# Footer
footer_show_references: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-sitemap