# Site
repository: JuliaHappyLongevity/JuliaHappyLongevity.github.io
favicon: images/favicon.ico

# Content configuration version
version: 1

# Personal info
name: Julia Persson
title: AI & Data Science Leader | HealthTech Innovator | Longevity Platform Founder
email: julia@happylongevity.life
description: >- 
  Building an AI-powered health optimization platform seeking exceptional data scientists and ML engineers.
  We're leveraging advanced analytics, deep learning, and predictive modeling to transform biomarker data
  into personalized health insights and actionable recommendations. Join our mission to democratize
  longevity science through innovative data approaches.
website: https://juliahappylongevity.github.io
baseurl: ""
url: "https://juliahappylongevity.github.io"

# Build settings
remote_theme: sproogen/modern-resume-theme

# Social links
github_username: JuliaHappyLongevity
linkedin_username: julia-persson-digital-transformation

# Site navigation
header_pages:
  - projects.md
  - join-us/index.md

# About Section
about_title: About Me
about_profile_image: /images/JP_founder.jpeg
about_content: | 
  Dedicated to democratising health optimisation, I focus on transforming complex health data into clear, actionable
  insights through AI technology and scientific frameworks.

  Drawing on decades of experience in digital transformation and strategic business execution, combined with an
  extensive personal health optimisation journey, I work to empower everyone to understand their health patterns and
  take early action.

  Through HappyLongevity, AI-Powered Longevity Navigation Platform, we aim to deliver AI-enabled, data-driven insights and practical solutions that make preventive
  health optimisation accessible and understandable for all - because staying healthy shouldn't require a medical degree.

# Dark Mode (true/false/never)
darkmode: false

# Google Analytics
google_analytics: G-EMBYLELM4B  # Replace with your actual Google Analytics ID

# Footer
footer_show_references: true
references_title: References on request

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme