# Site
repository: JuliaHappyLongevity/JuliaHappyLongevity.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Julia Persson
title: Digital Transformation Leader | HealthTech Innovator | AI-Augmented Venture Designer
email: julia@happylongevity.life
website: https://happylongevity.life
description: >- 
  Digital Transformation Leader and HealthTech Innovator dedicated to democratizing 
  health optimization through AI and data-driven solutions. Founder of HappyLongevity.
url: "https://juliahappylongevity.github.io"
baseurl: ""

# Build settings
remote_theme: sproogen/modern-resume-theme

# Navigation
header_pages:
  - projects.md

# Social links
github_username: JuliaHappyLongevity
linkedin_username: julia-persson-digital-transformation

# Phone info removed

# Content sections
content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: HappyLongevity.Life
        sub_title: Founder
        caption: July 2024 - Present
        link: https://happylongevity.life
        description: |
          Building a data-driven health optimization platform, integrating biomarkers, wearables, and AI. Developing scientific validation frameworks, focusing on longevity and preventive healthcare.
          
          - Implementing AI-driven health analysis and personalized recommendations
          - Creating data integration frameworks for biomarkers and wearable devices
          - Developing digital marketing, SEO strategy, and online community
          - Building scientific validation protocols with multi-LLM architecture
          
      - layout: right
        title: Accenture
        sub_title: Managing Director, Nordic Cloud Financial Services and Health & Public Sector Lead
        caption: Sep 2021 - March 2025
        link: https://www.accenture.com
        description: |
          Led regulated industries portfolio (Financial Services, Public Sector & Healthcare) managing cloud adoption, digital transformation and large-scale migrations.
          
          - Aligned technology strategies with compliance requirements
          - Managed global engagements across financial services, healthcare, and public sector
          - Implemented data-driven decision frameworks for enterprise clients
          
      - layout: right
        title: Amazon Web Services (AWS)
        sub_title: Financial Services Lead
        caption: Feb 2019 - Aug 2021
        link: https://aws.amazon.com
        description: |
          Achieved exponential growth in Nordic FS through data-driven strategy and cloud adoption.
          
          - Led major cloud transformation projects for banks, insurers, and pension providers
          - Implemented enterprise-scale data and analytics solutions
          - Developed scalable architectures for regulated industries
          - Created strategic technology roadmaps for digital transformation
          
      - layout: right
        title: Swedbank
        sub_title: Head of Cash Management, Large Corporates & Institutions
        caption: Apr 2013 - Jan 2019
        link: https://www.swedbank.com
        description: |
          Delivered revenue growth, increasing client engagement through digital innovation.
          
          - Led business transformation programs
          - Aligned financial services with digital technology
          - Implemented data-driven client solutions
          - Optimized operational efficiency through technology
          
      - layout: right
        title: A.P. Moller-Maersk
        sub_title: Deputy Head of Corporate Treasury
        caption: Jan 2007 - Mar 2013
        link: https://www.maersk.com
        description: |
          Managed global banking operations across 120+ countries, optimizing cash management.
          
          - Improved liquidity visibility to 87%
          - Reduced idle cash below 10% during the financial crisis
          - Implemented global treasury systems
          - Standardized financial processes across regions
          
  - title: Current Projects
    layout: list
    content:
      - layout: left
        title: <div style="text-align: center; margin-bottom: 15px;"><img src="/images/HL_logo.png" alt="HappyLongevity Logo" style="max-width: 250px;"></div>HappyLongevity Platform
        link: https://juliahappylongevity.github.io/project/
        link_text: View Platform Details
        additional_links:
          - title: JuliaHappyLongevity/JuliaHappyLongevity.github.io
            icon: fab fa-github
            url: https://github.com/JuliaHappyLongevity/JuliaHappyLongevity.github.io
        quote: >
          Seeking Data Science Talent & Bioscience researchers for collaboration
        description: |
          Building a data-driven health optimization platform, uniting science and AI. This AI-powered Longevity Navigation platform integrates biomarkers, genetic data, wearables, and lifestyle factors to provide early health risk detection and personalized recommendations.
          
          **Our Approach:**
          - Scientific Validation - Rigorous frameworks based on medical research
          - AI-Powered Analysis - Multi-LLM architecture for reliable health insights
          - Data Integration & Security - Creating a unified structure for diverse health data sources with privacy and security by design
          - Personalized Recommendations - Tailored health optimization strategies
          - Early Risk Detection - Identifying patterns before they become problems
          
      - layout: left
        title: Nordic Women's Health Hub
        quote: >
          Volunteer Initiative
        description: |
          Co-leading Nordic Women's Health Vision 2040, a volunteer initiative to improve women's health outcomes through technology, education, and policy.
      
      - layout: left
        title: ReDI School of Digital Integration
        quote: >
          Volunteer Initiative
        description: |
          Teaching technology fundamentals to women from foreign backgrounds, empowering them with digital skills for career advancement.

  - title: Background
    layout: text
    content: |
      <div class="columns-container">
        <div class="column">
          <h4 style="font-size: 1rem;">Education</h4>
          <ul style="font-size: 0.9rem; margin-top: 0.5rem;">
            <li>MSc in Business & Economics<br/><em>Lund University</em></li>
            <li>MSc in Business Administration<br/><em>Kyiv National Economic University</em></li>
          </ul>
        </div>
        
        <div class="column">
          <h4 style="font-size: 1rem;">Certifications</h4>
          <ul style="font-size: 0.9rem; margin-top: 0.5rem;">
            <li>MIT Sloan – Green Cloud & Business Transformation</li>
            <li>Harvard Business School – Disruptive Strategy & Leadership</li>
            <li>AWS Cloud Practitioner</li>
            <li>IMD – Financial Leadership Program</li>
          </ul>
        </div>
        
        <div class="column">
          <h4 style="font-size: 1rem;">Languages</h4>
          <ul style="font-size: 0.9rem; margin-top: 0.5rem;">
            <li><strong>English:</strong> Fluent</li>
            <li><strong>Swedish:</strong> Fluent</li>
            <li><strong>Ukrainian:</strong> Fluent</li>
            <li><strong>Russian:</strong> Fluent</li>
            <li><strong>Danish:</strong> Conversational</li>
          </ul>
        </div>
      </div>
      
      <style>
      .columns-container {
        display: flex;
        flex-wrap: wrap;
        gap: 2rem;
      }
      .column {
        flex: 1;
        min-width: 200px;
      }
      </style>

# About Section
about_title: About Me
about_profile_image: /images/JP_founder.jpeg
about_content: | 
  Dedicated to democratizing health optimization, Julia focuses on transforming complex health data into clear, actionable insights through AI technology and scientific frameworks.
  
  Drawing on decades of experience in digital transformation and strategic business execution, combined with an extensive personal health optimization journey, she works to empower everyone to understand their health patterns and take early action. 
  
  Through HappyLongevity, she aims to deliver AI-enabled, data-driven insights and practical solutions that make preventive health optimization accessible and understandable for all - because staying healthy shouldn't require a medical degree.

# Dark Mode (true/false/never)
darkmode: false

# Google Analytics
google_analytics: G-EMBYLELM4B  # Replace with your actual Google Analytics ID

# Footer
footer_show_references: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-sitemap

header_links:
  - text: Profile
    url: /
  - text: Project
    url: /project/